scss_files: "_sass/*.scss"

exclude: "css/style.scss"

linters:
  VendorPrefix:
    enabled: false
  TrailingWhitespace:
    enabled: false
  PseudoElement:
    enabled: false
  LeadingZero:
    enabled: true
    style: include_zero
  StringQuotes:
    eanbled: true
    style: double_quotes
